### ISSUE TITLE
TID tag not handled correctly with multiple tags, in some cases

### ISSUE THREAD

**Issue by alb-i986** [HPSoftware/octane-cucumber-jvm#8] opened 2017-09-14 14:18 UTC
https://github.com/HPSoftware/octane-cucumber-jvm/blob/44e295362c0014e834ed64332b5442b0ef7220c1/src/main/java/com/hpe/alm/octane/HPEAlmOctaneGherkinFormatter.java#L68-L71

It's limiting: in case a Feature has multiple tags, `HPEAlmOctaneGherkinFormatter` is going to correctly find a `@TID` tag if and only if the `@TID` tag is the first one.

So for example, Given the following feature file:

```
@TID1001REV0.1.0
@OtherTag
Feature: Login
  Scenario: scenario1
    Given ...

...
````

`HPEAlmOctaneGherkinFormatter` will correctly parse the `@TID` tag.

But with the feature file below, the report will not contain the TID tag:
```
@OtherTag
@TID1001REV0.1.0
Feature: Login
  Scenario: scenario1
    Given ...

...
````

**Comment by sharonvardi** [comment] 2017-10-02 11:28
The issue is fixed on version 12.55.7

**Closed as completed by sharonvardi** 2017-10-02 11:28 UTC
